version: "2"

services:

  php:
    build:
      context: './php/'
      args:
       PHP_VERSION: ${PHP_TAG}
    container_name: "${PROJECT_NAME}_php"
    networks:
      - backend
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
    volumes:
        - ./../:/usr/local/apache2/htdocs/
        - ./php/php.ini:/usr/local/etc/php/php.ini

  httpd:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    container_name: "${PROJECT_NAME}_httpd"
    depends_on:
        - php
        - mysqld
    networks:
      - frontend
      - backend
    ports:
      - '80:80'
      # - '443:8443'
    volumes:
        - ./../:/usr/local/apache2/htdocs
    labels:
      - 'traefik.backend=httpd'
      - 'traefik.port=80'
      - "traefik.frontend.rule=Host:${PROJECT_BASE_URL}"

  mysqld:
    image: mysql:$MYSQLDB_TAG
    container_name: "${PROJECT_NAME}_mysqldb"
    stop_grace_period: 30s
    # external_links:
        # - mysql_mysql_1:docker-mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      # DB_HOST: docker-mysql
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
        - ./db/:/home/

  traefik:
    image: traefik
    container_name: "${PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      #- "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  frontend:
  backend:
volumes:
## Uncomment for macOS
  docker-sync7:
    external: true
  docker-sync-mysql:
    external: true
